### ISSUE TITLE
Cannot open file internal error

### ISSUE THREAD

**Issue by Halama** [keboola/processor-add-filename-column#3]
https://connection.keboola.com/admin/utils/logs?file=2018/05/09/14/2018-05-09-14-28-20-5af2e9644f29e-exception

https://keboola.zendesk.com/agent/tickets/8370

Vypadá to že by ho to mělo proiterovat jako sliced soubor ale místo toho ho to otevírá napřímo.

**Comment by ondrejhlavacek** [comment]
a) chybí stack trace
b) mohlo by to umět proiterovat nekonečný adresářový struktury a nebo vyhodit user chybu, že jde o složitější podadresáře

**Comment by Halama** [comment]
A bylo to teda tím že do toho vstupovala zanořená adresářová struktura, po dekompresi zapomněli přidat flatten-files procesor.

**Comment by odinuv** [comment]
ja bych rekl, ze to ma byt user-error, od toho tam je ten flatten procesor (nebo ho zrusme)

**Comment by ondrejhlavacek** [comment]
Hodím do message teda zmínku o flatten procesoru?

**Comment by ondrejhlavacek** [comment]
To samý bude platit pro https://github.com/keboola/processor-add-row-number-column

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/processor-flatten-folders/issues/2

**Comment by ondrejhlavacek** [comment]
v obou fixnuto, hodíte na to někdo rychlý oko? mergnu, deploynu
